export { LoginScreen as ScreenLogin } from "./Login"
export { RegisterScreen as ScreenRegister } from "./Register"
export { PerfilScreen as ScreenPerfil } from "./Perfil"
export { ListVinylRecordsScreen as ScreenListVinylRecords } from "./Vinyl/ListVinylRecords"
export { VinylRecordDetailsScreen as ScreenVinylRecordDetails } from "./Vinyl/VinylRecordDetails"
export { RegisterVinylRecordScreen as ScreenRegisterVinylRecord } from "./Vinyl/RegisterVinylRecord"
export { EditVinylRecordScreen as ScreenEditVinylRecord } from "./Vinyl/EditVinylRecord"
export { PhotoScreen as ScreenPhoto } from "./Camera/Photo"